/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f746xx.h"
#include "reg_util.h"

void SystemClock_Setup(void);

int main(void)
{
	/* Loop forever */
	for (;;)
		;
}

void SystemClock_Setup(void)
{
	RCC_TypeDef *pRCC = RCC;

	/* Setting up main PLL
	 * PLL_M
	 * PLL_N
	 * PLL_P
	 * */
	REG_SET_VAL(pRCC->PLLCFGR, 0x8U, 0x3FU, RCC_PLLCFGR_PLLM_Pos);
	REG_SET_VAL(pRCC->PLLCFGR, 0x216U, 0x1FFU, RCC_PLLCFGR_PLLN_Pos);
	REG_SET_VAL(pRCC->PLLCFGR, 0x0U, 0x03U, RCC_PLLCFGR_PLLP_Pos);
}
